---
version: '3.4'
name: groceries
services:
  app:
    user: "936"
    image: groceries:latest
    expose:
      - 3000
    volumes:
      - /data/groceries/storage:/rails/storage
    environment:
      # VIRTUAL_HOST: groceries.guymon.family
      # VIRTAUL_PORT: 3000
      # LETSENCRYPT_HOST: groceries.guymon.family
      SECRET_KEY_BASE: na
    networks:
      - cloudflare

networks:
  cloudflare:
    external: true
